name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: List the contents of the repository to verify if 'public' is present
    - name: List directory contents
      run: ls -la

    # Step 3: Upload the 'public' directory as an artifact for deployment
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public  # Make sure this is the path where your files are

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
