# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when you push to the 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
     name: github-pages
     url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 2: Upload static files to GitHub Pages
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public  # Replace with your folder (e.g., 'dist' or 'build')

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
